#!/usr/bin/env bash
#
# himalaya-gmail-setup.sh — set up himalaya for Gmail on a new machine.
#
# Interactive: it asks for your Gmail address, display name and Gmail App
# Password, then writes the himalaya config and verifies the connection.
#
#   1. Installs the himalaya binary if missing (to ~/.local)
#   2. Asks for: Gmail address, display name, App Password
#   3. Writes the config and the app-password file (chmod 600)
#   4. Verifies with `himalaya account check`
#
# ============================================================
# GET THE GMAIL APP PASSWORD HERE:
#   https://myaccount.google.com/apppasswords
# (Google Account -> Security -> 2-Step Verification -> App passwords.
#  2-Step Verification must be enabled on the account first. The password
#  is 16 letters in 4 groups, like: abcd efgh ijkl mnop)
# ============================================================
#
# The App Password is typed into a hidden prompt and written only to the
# local file below — it is never echoed or logged.
#
# Usage: bash himalaya-gmail-setup.sh

set -euo pipefail

APP_PASSWORDS_URL="https://myaccount.google.com/apppasswords"
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/himalaya"
CONFIG_FILE="$CONFIG_DIR/config.toml"
SECRET_FILE="$CONFIG_DIR/.app-password"

say() { printf '%s\n' "$*"; }

# --- 1. himalaya binary ---------------------------------------------------
if ! command -v himalaya >/dev/null 2>&1; then
  say "himalaya is not installed."
  printf 'Install it now to ~/.local? [Y/n] '
  read -r answer
  case "$answer" in
    [Nn]*)
      say "Install manually, then re-run this script:"
      say "  curl -sSL https://raw.githubusercontent.com/pimalaya/himalaya/master/install.sh | PREFIX=\"\$HOME/.local\" sh"
      exit 1
      ;;
  esac
  curl -sSL https://raw.githubusercontent.com/pimalaya/himalaya/master/install.sh | PREFIX="$HOME/.local" sh
  export PATH="$HOME/.local/bin:$PATH"
  if ! command -v himalaya >/dev/null 2>&1; then
    say "Installed, but himalaya is not on PATH. Add \$HOME/.local/bin to PATH and re-run."
    exit 1
  fi
fi
say "Using: $(himalaya --version | head -n1)"

# --- 2. gather info -------------------------------------------------------
say ""
say "Answer the following (display name may be left blank)."
while :; do
  printf 'Gmail address: '
  read -r EMAIL
  case "$EMAIL" in
    *@*.*) break ;;
    *) say "  That does not look like an email address." ;;
  esac
done

printf 'Display name (From name), blank for none: '
read -r DISPLAY_NAME

say ""
say "Now the Gmail App Password:"
say "  1. Open: $APP_PASSWORDS_URL"
say "     (Google Account -> Security -> 2-Step Verification -> App passwords;"
say "      2-Step Verification must be ON. You can generate a fresh one anytime.)"
say "  2. Copy the 16-letter password (like: abcd efgh ijkl mnop)."
say ""
printf 'App password (hidden input, blank to fill in later): '
read -r -s APP_PASSWORD
say ""

# reject characters that would break the TOML
for val in "$EMAIL" "$DISPLAY_NAME"; do
  case "$val" in
    *\"*|*\\*)
      say "Error: double quotes and backslashes are not allowed in the answers."
      exit 1
      ;;
  esac
done

# --- 3. write files -------------------------------------------------------
mkdir -p "$CONFIG_DIR"
umask 077

if [ -f "$CONFIG_FILE" ]; then
  backup="$CONFIG_FILE.bak.$(date +%Y%m%d%H%M%S)"
  mv "$CONFIG_FILE" "$backup"
  say "Existing config backed up to $backup"
fi

{
  printf '# himalaya v2 config — generated by himalaya-gmail-setup.sh\n'
  printf '# Schema: https://github.com/pimalaya/himalaya/blob/master/config.sample.toml\n'
  printf '# Note: v2 config keys differ from v1; v1 keys are silently ignored.\n\n'
  if [ -n "$DISPLAY_NAME" ]; then
    printf 'display-name = "%s"\n' "$DISPLAY_NAME"
    printf 'downloads-dir = "~/Downloads/himalaya"\n\n'
  fi
  printf '[accounts.gmail]\n'
  printf 'default = true\n'
  printf 'email = "%s"\n' "$EMAIL"
  if [ -n "$DISPLAY_NAME" ]; then
    printf 'display-name = "%s"\n' "$DISPLAY_NAME"
  fi
  printf '\n# IMAP (reading)\n'
  printf 'imap.server = "imaps://imap.gmail.com:993"\n'
  printf 'imap.sasl.plain.username = "%s"\n' "$EMAIL"
  printf 'imap.sasl.plain.password.command = "cat %s"\n' "$SECRET_FILE"
  printf '\n# SMTP (sending), implicit TLS on 465\n'
  printf 'smtp.server = "smtps://smtp.gmail.com:465"\n'
  printf 'smtp.sasl.plain.username = "%s"\n' "$EMAIL"
  printf 'smtp.sasl.plain.password.command = "cat %s"\n' "$SECRET_FILE"
  printf '\n# Gmail mailbox mapping (Sent is [Gmail]/Sent Mail, not "Sent")\n'
  printf 'mailbox.alias.inbox = "INBOX"\n'
  printf 'mailbox.alias.sent = "[Gmail]/Sent Mail"\n'
  printf 'mailbox.alias.drafts = "[Gmail]/Drafts"\n'
  printf 'mailbox.alias.trash = "[Gmail]/Trash"\n'
} > "$CONFIG_FILE"
chmod 600 "$CONFIG_FILE"
say "Wrote $CONFIG_FILE"

if [ -n "$APP_PASSWORD" ]; then
  printf '%s' "$APP_PASSWORD" > "$SECRET_FILE"
  chmod 600 "$SECRET_FILE"
  unset APP_PASSWORD
  say "Wrote $SECRET_FILE"
else
  say ""
  say "No app password entered. When you have one, put it in the file yourself:"
  say "  printf '%s' 'YOUR-APP-PASSWORD' > $SECRET_FILE && chmod 600 $SECRET_FILE"
fi

# --- 4. verify ------------------------------------------------------------
say ""
if [ ! -s "$SECRET_FILE" ]; then
  say "Skipping connection check (no app password yet). Verify later with:"
  say "  himalaya account check"
  exit 0
fi

say "Verifying connection..."
check_rc=0
check_out="$(himalaya account check 2>&1)" || check_rc=$?
say "$check_out"
# NB: `himalaya account check` exits 0 even when a backend reports FAIL,
# so decide on the output, not the exit code.
if [ "$check_rc" -eq 0 ] && ! printf '%s' "$check_out" | grep -q 'FAIL'; then
  say ""
  say "Done. Try: himalaya envelope list"
else
  say ""
  say "Connection check failed. Most likely the app password is wrong, expired,"
  say "or 2-Step Verification is not enabled on the account."
  say "Get a fresh app password at: $APP_PASSWORDS_URL"
  say "then overwrite the secret and re-check:"
  say "  printf '%s' 'YOUR-APP-PASSWORD' > $SECRET_FILE && chmod 600 $SECRET_FILE"
  say "  himalaya account check"
  exit 1
fi
